### ISSUE TITLE
read_ini_file_mpi

### ISSUE THREAD

**Issue by dkolom** [pseudospectators/FLUSI#16]
In read_ini_file_mpi, the first check
    inquire ( file=file, exist=exists )
    if ( exists .eqv. .false.) then
      write (*,'("ERROR! file: ",A," not found")') trim(adjustl(file))
      call MPI_abort(MPI_COMM_WORLD, 86552, mpicode)
    endif
is redundant and, in addition, the code fails at startup if the mpi processes don't share the same disk space. Maybe remove these lines.

**Comment by tommy-engels** [comment]
you're completely right, changes commited.

**Comment by dkolom** [comment]
Thanks!
