### ISSUE TITLE
Why nx/2, ny/2, nz/2?

### ISSUE THREAD

**Issue by dkolom** [pseudospectators/FLUSI#19]
https://github.com/pseudospectators/FLUSI/blob/819b6e9c0d9b7d2d7819ecb6c35e7425ec9e3044/src/file_io/flusi_hdf5_interface.f90#L157

**Comment by tommy-engels** [comment]
you're right: this seems to be a bug.
I guess its a leftover from the time we had only 2 striding or no striding -- I'll correct it

**Comment by dkolom** [comment]
Thanks!
